name: synchealthlabs/github-action-teams
description: Github Action Notifier for Microsoft Teams
author: Sync Health Labs
inputs:
  github-token:
    required: true
    description: Github token
  webhook-uri:
    required: true
    description: Microsoft Teams webhook uri
  type:
    required: true
    description: start or finish
  status:
    description: "Job status i.e. Success/Failure/Cancelled"
    required: true
  email:
    description: Email of the person requesting the job
    required: true
  name:
    description: Name of the person requesting the job
    required: true
  message:
    description: Commit message
    required: true
  publish-url: 
    required: false
    description: Publish url 

runs:
  using: node12
  main: dist/main/index.js